[workspace]
members = [
    "crates/beryl",
    "crates/beryl-app",
    "crates/beryl-backend",
    "crates/beryl-home-store",
    "crates/beryl-model",
    "crates/beryl-state",
    "crates/beryl-stream",
    "crates/syndic-storage",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.92"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
bounded-json = { path = "../bounded-json" }
beryl-app = { path = "crates/beryl-app" }
beryl-backend = { path = "crates/beryl-backend" }
beryl-home-store = { path = "crates/beryl-home-store" }
beryl-model = { path = "crates/beryl-model" }
beryl-state = { path = "crates/beryl-state" }
beryl-stream = { path = "crates/beryl-stream" }
syndic-storage = { path = "crates/syndic-storage" }
clap = { version = "4.6.1", features = ["derive"] }
fjall = { path = "../fjall-fork", version = "=3.1.6" }
getrandom = "0.4.2"
hex = "0.4.3"
gpui = { git = "https://github.com/berylorg/zed-fork.git", rev = "8984628759b87ecfea7c7ae593c972a0dbfb8d30", default-features = false, features = ["windows-manifest"] }
gpui-scrollbar = { git = "https://github.com/berylorg/gpui-scrollbar.git", rev = "9dd6b6af4764bfd0986c6a9c23bb9c80390baa01" }
gpui-settings-window = { git = "https://github.com/berylorg/gpui-settings-window.git", rev = "ea642371cd6eee80256bed3dc38df7a2e0fc4463" }
gpui-text-input = { git = "https://github.com/berylorg/gpui-text-input.git", rev = "d21bf52c8f5f8a7d76887bce87c5dbc1c6c8f2d3" }
gpui_sum_tree = "0.2.2"
image = "0.25.1"
jsonc-parser = { version = "0.32.4", default-features = false }
markdown = { version = "1.0.0", default-features = false }
once_cell = "1.21.4"
regex = "1.12.3"
raw-window-handle = "0.6.2"
rodio = { version = "0.22.2", default-features = false, features = ["playback", "hound"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
shlex = "1.3.0"
soketto = { version = "0.8.1", default-features = false }
tempfile = "3.27.0"
taplo = { version = "0.14.0", default-features = false }
thiserror = "2.0.18"
toml = "0.9.12"
tokio = { version = "1.52.1", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.18", default-features = false, features = ["compat"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
tungstenite = { version = "0.29.0", default-features = false, features = ["handshake"] }
unicode-segmentation = "1.12.0"
unicode-normalization = "=0.1.25"
wait-timeout = "0.2.1"
windows = "0.61"
