/// One exact Syndic current-domain family selected for a bounded physical corruption fixture.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PhysicalFamily {
    Threads,
    ImageLabelAuthorityHeads,
    DraftImageLabelProtectionHeads,
    ThreadExecutions,
    ThreadAttributes,
    ThreadUsage,
    ThreadCatalogSummaries,
    Drafts,
    ContentManifests,
    ContentChunks,
    ContentByteSpans,
    ContentTextSpans,
    ContentPieces,
    ProviderNarrativeSpans,
    ProviderItemBuilds,
    ProviderObservationBuilds,
    ProviderObservationChunks,
    ContextEnvelopes,
    Turns,
    TurnStates,
    InputGates,
    AcceptedInputs,
    StopOperations,
    CompactionOperations,
    CompactionSettlementReceipts,
    AcceptedRouteGenerationHeads,
    AcceptedRouteLeaves,
    SourceEvents,
    CanonicalItems,
    ActivityQueryHeads,
    ItemProjectionHeads,
    ItemProjectionSets,
    ItemProjectionBuilds,
    TranscriptViewHeads,
    TranscriptBuilds,
    Projections,
    Resources,
    HistorySummaries,
    Bindings,
    ExecutionSnapshots,
    ActiveCasTurns,
    DraftByThread,
    ThreadParent,
    ImageLabelOriginSpans,
    TurnChildren,
    AcceptedOrder,
    AcceptedRouteGenerations,
    AcceptedReadySources,
    AcceptedNextSources,
    TurnItems,
    ActivityQueryEntries,
    ActivityQuerySources,
    ItemSourceEvents,
    CasItem,
    TranscriptPathTurns,
    TranscriptViewEntries,
    StableItemProjections,
    ItemProjections,
    ProjectionResources,
    BindingHeads,
    CasThread,
    CasThreadBinding,
    CasTurn,
}

impl PhysicalFamily {
    pub const ALL: [Self; 63] = [
        Self::Threads,
        Self::ImageLabelAuthorityHeads,
        Self::DraftImageLabelProtectionHeads,
        Self::ThreadExecutions,
        Self::ThreadAttributes,
        Self::ThreadUsage,
        Self::ThreadCatalogSummaries,
        Self::Drafts,
        Self::ContentManifests,
        Self::ContentChunks,
        Self::ContentByteSpans,
        Self::ContentTextSpans,
        Self::ContentPieces,
        Self::ProviderNarrativeSpans,
        Self::ProviderItemBuilds,
        Self::ProviderObservationBuilds,
        Self::ProviderObservationChunks,
        Self::ContextEnvelopes,
        Self::Turns,
        Self::TurnStates,
        Self::InputGates,
        Self::AcceptedInputs,
        Self::StopOperations,
        Self::CompactionOperations,
        Self::CompactionSettlementReceipts,
        Self::AcceptedRouteGenerationHeads,
        Self::AcceptedRouteLeaves,
        Self::SourceEvents,
        Self::CanonicalItems,
        Self::ActivityQueryHeads,
        Self::ItemProjectionHeads,
        Self::ItemProjectionSets,
        Self::ItemProjectionBuilds,
        Self::TranscriptViewHeads,
        Self::TranscriptBuilds,
        Self::Projections,
        Self::Resources,
        Self::HistorySummaries,
        Self::Bindings,
        Self::ExecutionSnapshots,
        Self::ActiveCasTurns,
        Self::DraftByThread,
        Self::ThreadParent,
        Self::ImageLabelOriginSpans,
        Self::TurnChildren,
        Self::AcceptedOrder,
        Self::AcceptedRouteGenerations,
        Self::AcceptedReadySources,
        Self::AcceptedNextSources,
        Self::TurnItems,
        Self::ActivityQueryEntries,
        Self::ActivityQuerySources,
        Self::ItemSourceEvents,
        Self::CasItem,
        Self::TranscriptPathTurns,
        Self::TranscriptViewEntries,
        Self::StableItemProjections,
        Self::ItemProjections,
        Self::ProjectionResources,
        Self::BindingHeads,
        Self::CasThread,
        Self::CasThreadBinding,
        Self::CasTurn,
    ];

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Threads => "threads",
            Self::ImageLabelAuthorityHeads => "image-label-authority-heads",
            Self::DraftImageLabelProtectionHeads => "draft-image-label-protection-heads",
            Self::ThreadExecutions => "thread-executions",
            Self::ThreadAttributes => "thread-attributes",
            Self::ThreadUsage => "thread-usage",
            Self::ThreadCatalogSummaries => "thread-catalog-summaries",
            Self::Drafts => "drafts",
            Self::ContentManifests => "content-manifests",
            Self::ContentChunks => "content-chunks",
            Self::ContentByteSpans => "content-byte-spans",
            Self::ContentTextSpans => "content-text-spans",
            Self::ContentPieces => "content-pieces",
            Self::ProviderNarrativeSpans => "provider-narrative-spans",
            Self::ProviderItemBuilds => "provider-item-builds",
            Self::ProviderObservationBuilds => "provider-observation-builds",
            Self::ProviderObservationChunks => "provider-observation-chunks",
            Self::ContextEnvelopes => "context-envelopes",
            Self::Turns => "turns",
            Self::TurnStates => "turn-states",
            Self::InputGates => "input-gates",
            Self::AcceptedInputs => "accepted-inputs",
            Self::StopOperations => "stop-operations",
            Self::CompactionOperations => "compaction-operations",
            Self::CompactionSettlementReceipts => "compaction-settlement-receipts",
            Self::AcceptedRouteGenerationHeads => "accepted-route-generation-heads",
            Self::AcceptedRouteLeaves => "accepted-route-leaves",
            Self::SourceEvents => "source-events",
            Self::CanonicalItems => "canonical-items",
            Self::ActivityQueryHeads => "activity-query-heads",
            Self::ItemProjectionHeads => "item-projection-heads",
            Self::ItemProjectionSets => "item-projection-sets",
            Self::ItemProjectionBuilds => "item-projection-builds",
            Self::TranscriptViewHeads => "transcript-view-heads",
            Self::TranscriptBuilds => "transcript-builds",
            Self::Projections => "projections",
            Self::Resources => "resources",
            Self::HistorySummaries => "history-summaries",
            Self::Bindings => "bindings",
            Self::ExecutionSnapshots => "execution-snapshots",
            Self::ActiveCasTurns => "active-cas-turns",
            Self::DraftByThread => "draft-by-thread",
            Self::ThreadParent => "thread-parent-index",
            Self::ImageLabelOriginSpans => "image-label-origin-spans",
            Self::TurnChildren => "turn-children",
            Self::AcceptedOrder => "accepted-order",
            Self::AcceptedRouteGenerations => "accepted-route-generations",
            Self::AcceptedReadySources => "accepted-ready-sources",
            Self::AcceptedNextSources => "accepted-next-sources",
            Self::TurnItems => "turn-items",
            Self::ActivityQueryEntries => "activity-query-entries",
            Self::ActivityQuerySources => "activity-query-sources",
            Self::ItemSourceEvents => "item-source-events",
            Self::CasItem => "cas-item-index",
            Self::TranscriptPathTurns => "transcript-path-turns",
            Self::TranscriptViewEntries => "transcript-view-entries",
            Self::StableItemProjections => "stable-item-projections",
            Self::ItemProjections => "item-projections",
            Self::ProjectionResources => "projection-resources",
            Self::BindingHeads => "binding-heads",
            Self::CasThread => "cas-thread-index",
            Self::CasThreadBinding => "cas-thread-bindings",
            Self::CasTurn => "cas-turn-index",
        }
    }
}
