pub const NOTICE_RECORD_CAPACITY: usize = 16;
pub const NOTICE_TITLE_BYTES: usize = 256;
pub const NOTICE_DETAIL_BYTES: usize = 4096;
pub const NOTICE_COMMAND_CAPACITY: usize = 3;
pub const NOTICE_COMMAND_LABEL_BYTES: usize = 96;
pub const NOTICE_COMMAND_REASON_BYTES: usize = 256;
pub const NOTICE_RECORD_TEXT_BYTES: usize = NOTICE_TITLE_BYTES
    + NOTICE_DETAIL_BYTES
    + NOTICE_COMMAND_CAPACITY * (NOTICE_COMMAND_LABEL_BYTES + NOTICE_COMMAND_REASON_BYTES);
