#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BerylThemeProperty {
    Background,
    Border,
    Foreground,
    TextBackground,
    FontFamily,
    FontSize,
    FontWeight,
}

impl BerylThemeProperty {
    pub const ALL: &'static [Self] = &[
        Self::Background,
        Self::Border,
        Self::Foreground,
        Self::TextBackground,
        Self::FontFamily,
        Self::FontSize,
        Self::FontWeight,
    ];

    pub fn id(self) -> &'static str {
        match self {
            Self::Background => "background",
            Self::Border => "border",
            Self::Foreground => "foreground",
            Self::TextBackground => "text_background",
            Self::FontFamily => "font_family",
            Self::FontSize => "font_size",
            Self::FontWeight => "font_weight",
        }
    }
}

macro_rules! define_beryl_theme_roles {
    ($( $variant:ident => ($id:literal, $parent:expr), )+) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum BerylThemeRole {
            $( $variant, )+
        }

        impl BerylThemeRole {
            pub const ALL: &'static [Self] = &[
                $( Self::$variant, )+
            ];

            pub fn id(self) -> &'static str {
                match self {
                    $( Self::$variant => $id, )+
                }
            }

            pub fn static_parent(self) -> Option<Self> {
                match self {
                    $( Self::$variant => $parent, )+
                }
            }
        }

        pub const BUILT_IN_THEME_ROLE_INVENTORY: &[&str] = &[
            $( $id, )+
        ];
    };
}

define_beryl_theme_roles! {
    AppWindow => ("app.window", None),
    MainToolbar => ("main.toolbar", Some(BerylThemeRole::AppWindow)),
    MainThreadStrip => ("main.thread_strip", Some(BerylThemeRole::AppWindow)),
    MainSeparator => ("main.separator", Some(BerylThemeRole::AppWindow)),
    Panel => ("panel", Some(BerylThemeRole::AppWindow)),
    SurfaceRow => ("row", Some(BerylThemeRole::Panel)),
    SurfaceRowHover => ("row.hover", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowSelected => ("row.selected", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowDisabled => ("row.disabled", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowPending => ("row.pending", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowUnavailable => ("row.unavailable", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowError => ("row.error", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowWarning => ("row.warning", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowInfo => ("row.info", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowSuccess => ("row.success", Some(BerylThemeRole::SurfaceRow)),
    StructuralSeparator => ("structural.separator", Some(BerylThemeRole::AppWindow)),
    ButtonPrimaryNormal => ("button.primary.normal", Some(BerylThemeRole::AppWindow)),
    ButtonPrimaryHover => ("button.primary.hover", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryPressed => ("button.primary.pressed", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryActive => ("button.primary.active", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryDisabled => ("button.primary.disabled", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonSecondaryNormal => ("button.secondary.normal", Some(BerylThemeRole::AppWindow)),
    ButtonSecondaryHover => ("button.secondary.hover", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryPressed => ("button.secondary.pressed", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryActive => ("button.secondary.active", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryDisabled => ("button.secondary.disabled", Some(BerylThemeRole::ButtonSecondaryNormal)),
    InputPanel => ("input.panel", Some(BerylThemeRole::Panel)),
    InputField => ("input.field", Some(BerylThemeRole::InputPanel)),
    InputFieldFocused => ("input.field.focused", Some(BerylThemeRole::InputField)),
    InputSelection => ("input.selection", Some(BerylThemeRole::InputField)),
    InputCaret => ("input.caret", Some(BerylThemeRole::InputField)),
    InputError => ("input.error", Some(BerylThemeRole::InputField)),
    SettingsWindow => ("settings.window", Some(BerylThemeRole::AppWindow)),
    SettingsSidebar => ("settings.sidebar", Some(BerylThemeRole::SettingsWindow)),
    SettingsSidebarRowNormal => ("settings.sidebar.row.normal", Some(BerylThemeRole::SettingsSidebar)),
    SettingsSidebarRowHover => ("settings.sidebar.row.hover", Some(BerylThemeRole::SettingsSidebarRowNormal)),
    SettingsSidebarRowSelected => ("settings.sidebar.row.selected", Some(BerylThemeRole::SettingsSidebarRowNormal)),
    SettingsPage => ("settings.page", Some(BerylThemeRole::SettingsWindow)),
    SettingsGroup => ("settings.group", Some(BerylThemeRole::SettingsPage)),
    SettingsRowNormal => ("settings.row.normal", Some(BerylThemeRole::SettingsGroup)),
    SettingsRowHover => ("settings.row.hover", Some(BerylThemeRole::SettingsRowNormal)),
    SettingsRowModified => ("settings.row.modified", Some(BerylThemeRole::SettingsRowNormal)),
    SettingsRowDisabled => ("settings.row.disabled", Some(BerylThemeRole::SettingsRowNormal)),
    SettingsInputNormal => ("settings.input.normal", Some(BerylThemeRole::SettingsRowNormal)),
    SettingsInputFocused => ("settings.input.focused", Some(BerylThemeRole::SettingsInputNormal)),
    SettingsInputError => ("settings.input.error", Some(BerylThemeRole::SettingsInputNormal)),
    SettingsInputSelection => ("settings.input.selection", Some(BerylThemeRole::SettingsInputNormal)),
    SettingsPopup => ("settings.popup", Some(BerylThemeRole::PopupSurface)),
    SettingsButtonPrimary => ("settings.button.primary", Some(BerylThemeRole::ButtonPrimaryNormal)),
    SettingsButtonSecondary => ("settings.button.secondary", Some(BerylThemeRole::ButtonSecondaryNormal)),
    TranscriptShell => ("transcript.shell", Some(BerylThemeRole::AppWindow)),
    TranscriptAssistantFinal => ("transcript.turn.assistant.final", Some(BerylThemeRole::TranscriptShell)),
    TranscriptAssistantCommentary => ("transcript.turn.assistant.commentary", Some(BerylThemeRole::TranscriptAssistantFinal)),
    TranscriptAssistantReasoning => ("transcript.turn.assistant.reasoning", Some(BerylThemeRole::TranscriptAssistantFinal)),
    TranscriptUserInput => ("transcript.turn.user", Some(BerylThemeRole::TranscriptShell)),
    TranscriptActivityCaret => ("transcript.activity_caret", Some(BerylThemeRole::TranscriptShell)),
    TranscriptSelection => ("transcript.selection", Some(BerylThemeRole::TranscriptAssistantFinal)),
    TranscriptQuotePopup => ("transcript.quote_popup", Some(BerylThemeRole::PopupSurface)),
    TranscriptContextMenu => ("transcript.context_menu", Some(BerylThemeRole::PopupSurface)),
    TranscriptPending => ("transcript.pending", Some(BerylThemeRole::TranscriptShell)),
    TranscriptUnavailable => ("transcript.unavailable", Some(BerylThemeRole::TranscriptShell)),
    MarkdownParagraph => ("markdown.paragraph", Some(BerylThemeRole::TranscriptAssistantFinal)),
    MarkdownHeading => ("markdown.heading", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownEmphasis => ("markdown.emphasis", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownStrongEmphasis => ("markdown.strong_emphasis", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownInlineCode => ("markdown.inline_code", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownLink => ("markdown.link", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownBlockQuote => ("markdown.block_quote", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownListMarker => ("markdown.list_marker", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownThematicBreak => ("markdown.thematic_break", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownUnsupportedFallback => ("markdown.unsupported_fallback", Some(BerylThemeRole::MarkdownParagraph)),
    CodePanelContainer => ("code_panel.container", Some(BerylThemeRole::MarkdownParagraph)),
    CodePanelHeader => ("code_panel.header", Some(BerylThemeRole::CodePanelContainer)),
    CodePanelBody => ("code_panel.body", Some(BerylThemeRole::CodePanelContainer)),
    CodePanelBorder => ("code_panel.border", Some(BerylThemeRole::CodePanelContainer)),
    CodePanelSelection => ("code_panel.selection", Some(BerylThemeRole::CodePanelBody)),
    CodePanelResizeHandle => ("code_panel.resize_handle", Some(BerylThemeRole::CodePanelContainer)),
    CodePanelButtonNormal => ("code_panel.button.normal", Some(BerylThemeRole::ButtonSecondaryNormal)),
    CodePanelButtonHover => ("code_panel.button.hover", Some(BerylThemeRole::CodePanelButtonNormal)),
    CodePanelButtonActive => ("code_panel.button.active", Some(BerylThemeRole::CodePanelButtonNormal)),
    CodePanelButtonDisabled => ("code_panel.button.disabled", Some(BerylThemeRole::CodePanelButtonNormal)),
    SyntaxMarkupHeadingMarker => ("syntax.markup.heading_marker", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupQuoteMarker => ("syntax.markup.quote_marker", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupListMarker => ("syntax.markup.list_marker", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupThematicBreak => ("syntax.markup.thematic_break", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupFenceDelimiter => ("syntax.markup.fence_delimiter", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupFenceInfo => ("syntax.markup.fence_info", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupCodeBlock => ("syntax.markup.code_block", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupCodeSpanDelimiter => ("syntax.markup.code_span_delimiter", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupCodeSpan => ("syntax.markup.code_span", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupEmphasisDelimiter => ("syntax.markup.emphasis_delimiter", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupStrongDelimiter => ("syntax.markup.strong_delimiter", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupLinkText => ("syntax.markup.link_text", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupLinkDestination => ("syntax.markup.link_destination", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupImageMarker => ("syntax.markup.image_marker", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupPunctuation => ("syntax.markup.punctuation", Some(BerylThemeRole::CodePanelBody)),
    SyntaxMarkupHtml => ("syntax.markup.html", Some(BerylThemeRole::CodePanelBody)),
    SyntaxEscape => ("syntax.escape", Some(BerylThemeRole::CodePanelBody)),
    SyntaxStructuralPunctuation => ("syntax.structural_punctuation", Some(BerylThemeRole::CodePanelBody)),
    SyntaxKey => ("syntax.key", Some(BerylThemeRole::CodePanelBody)),
    SyntaxString => ("syntax.string", Some(BerylThemeRole::CodePanelBody)),
    SyntaxNumber => ("syntax.number", Some(BerylThemeRole::CodePanelBody)),
    SyntaxBoolean => ("syntax.boolean", Some(BerylThemeRole::CodePanelBody)),
    SyntaxNull => ("syntax.null", Some(BerylThemeRole::CodePanelBody)),
    SyntaxDateTime => ("syntax.date_time", Some(BerylThemeRole::CodePanelBody)),
    SyntaxComment => ("syntax.comment", Some(BerylThemeRole::CodePanelBody)),
    SyntaxSectionHeader => ("syntax.section_header", Some(BerylThemeRole::CodePanelBody)),
    SyntaxAssignment => ("syntax.assignment", Some(BerylThemeRole::CodePanelBody)),
    SyntaxTokenEscape => ("syntax.token_escape", Some(BerylThemeRole::CodePanelBody)),
    SyntaxError => ("syntax.error", Some(BerylThemeRole::CodePanelBody)),
    GraphOverlay => ("graph.overlay", Some(BerylThemeRole::Panel)),
    GraphColumn => ("graph.column", Some(BerylThemeRole::GraphOverlay)),
    GraphColumnHeader => ("graph.column_header", Some(BerylThemeRole::GraphColumn)),
    GraphRowTopic => ("graph.row.topic", Some(BerylThemeRole::GraphColumn)),
    GraphRowChecklist => ("graph.row.checklist", Some(BerylThemeRole::GraphColumn)),
    GraphRowChecklistItem => ("graph.row.checklist_item", Some(BerylThemeRole::GraphColumn)),
    GraphRowThreadRef => ("graph.row.thread_ref", Some(BerylThemeRole::GraphColumn)),
    GraphRowSoftLink => ("graph.row.soft_link", Some(BerylThemeRole::GraphColumn)),
    GraphRowHover => ("graph.row.hover", Some(BerylThemeRole::GraphColumn)),
    GraphRowSelected => ("graph.row.selected", Some(BerylThemeRole::GraphColumn)),
    GraphRowPending => ("graph.row.pending", Some(BerylThemeRole::GraphColumn)),
    GraphRowDisabled => ("graph.row.disabled", Some(BerylThemeRole::GraphColumn)),
    GraphRowInvalid => ("graph.row.invalid", Some(BerylThemeRole::GraphColumn)),
    GraphRowError => ("graph.row.error", Some(BerylThemeRole::GraphColumn)),
    ChecklistSidebar => ("checklist.sidebar", Some(BerylThemeRole::Panel)),
    ChecklistHeader => ("checklist.header", Some(BerylThemeRole::ChecklistSidebar)),
    ChecklistRow => ("checklist.row", Some(BerylThemeRole::ChecklistSidebar)),
    ChecklistStatusTodo => ("checklist.status.todo", Some(BerylThemeRole::ChecklistRow)),
    ChecklistStatusInProgress => ("checklist.status.in_progress", Some(BerylThemeRole::ChecklistRow)),
    ChecklistStatusDone => ("checklist.status.done", Some(BerylThemeRole::ChecklistRow)),
    ThreadSelectorSurface => ("thread_selector.surface", Some(BerylThemeRole::PopupSurface)),
    ThreadSelectorRow => ("thread_selector.row", Some(BerylThemeRole::ThreadSelectorSurface)),
    ThreadSelectorRowSelected => ("thread_selector.row.selected", Some(BerylThemeRole::ThreadSelectorRow)),
    ThreadSelectorRowUnavailable => ("thread_selector.row.unavailable", Some(BerylThemeRole::ThreadSelectorRow)),
    WorkspacePickerSurface => ("workspace_picker.surface", Some(BerylThemeRole::PopupSurface)),
    WorkspacePickerWorkspaceRow => ("workspace_picker.workspace_row", Some(BerylThemeRole::WorkspacePickerSurface)),
    WorkspacePickerMemberRow => ("workspace_picker.member_row", Some(BerylThemeRole::WorkspacePickerSurface)),
    WorkspacePickerRowActive => ("workspace_picker.row.active", Some(BerylThemeRole::WorkspacePickerSurface)),
    ColumnSelectorColumn => ("column_selector.column", Some(BerylThemeRole::PopupSurface)),
    ColumnSelectorHeader => ("column_selector.header", Some(BerylThemeRole::ColumnSelectorColumn)),
    ColumnSelectorRow => ("column_selector.row", Some(BerylThemeRole::ColumnSelectorColumn)),
    ColumnSelectorRowSelected => ("column_selector.row.selected", Some(BerylThemeRole::ColumnSelectorRow)),
    ColumnSelectorAccent => ("column_selector.accent", Some(BerylThemeRole::ColumnSelectorColumn)),
    PopupSurface => ("popup.surface", Some(BerylThemeRole::Panel)),
    PopupRowNormal => ("popup.row.normal", Some(BerylThemeRole::PopupSurface)),
    PopupRowHover => ("popup.row.hover", Some(BerylThemeRole::PopupRowNormal)),
    PopupRowSelected => ("popup.row.selected", Some(BerylThemeRole::PopupRowNormal)),
    PopupRowDisabled => ("popup.row.disabled", Some(BerylThemeRole::PopupRowNormal)),
    OverlayBackdrop => ("overlay.backdrop", Some(BerylThemeRole::AppWindow)),
    NoticeInfo => ("notice.info", Some(BerylThemeRole::PopupSurface)),
    NoticeWarning => ("notice.warning", Some(BerylThemeRole::PopupSurface)),
    NoticeError => ("notice.error", Some(BerylThemeRole::PopupSurface)),
    NoticeSuccess => ("notice.success", Some(BerylThemeRole::PopupSurface)),
    DiagnosticSurface => ("diagnostic.surface", Some(BerylThemeRole::Panel)),
    DiagnosticRow => ("diagnostic.row", Some(BerylThemeRole::DiagnosticSurface)),
    DiagnosticError => ("diagnostic.error", Some(BerylThemeRole::DiagnosticRow)),
    DiagnosticWarning => ("diagnostic.warning", Some(BerylThemeRole::DiagnosticRow)),
    StatusLine => ("status.line", Some(BerylThemeRole::AppWindow)),
    StatusValueWorking => ("status.value.working", Some(BerylThemeRole::StatusLine)),
    StatusValueCompacting => ("status.value.compacting", Some(BerylThemeRole::StatusLine)),
    StatusValueOk => ("status.value.ok", Some(BerylThemeRole::StatusLine)),
    StatusValueError => ("status.value.error", Some(BerylThemeRole::StatusLine)),
    StatusValuePending => ("status.value.pending", Some(BerylThemeRole::StatusLine)),
    StatusValueUnavailable => ("status.value.unavailable", Some(BerylThemeRole::StatusLine)),
    StatusValueStreaming => ("status.value.streaming", Some(BerylThemeRole::StatusLine)),
    ScrollbarThumbNormal => ("scrollbar.thumb.normal", Some(BerylThemeRole::AppWindow)),
    ScrollbarThumbHover => ("scrollbar.thumb.hover", Some(BerylThemeRole::ScrollbarThumbNormal)),
    ScrollbarThumbDragging => ("scrollbar.thumb.dragging", Some(BerylThemeRole::ScrollbarThumbNormal)),
    MediaPlaceholder => ("media.placeholder", Some(BerylThemeRole::TranscriptShell)),
    MediaPlaceholderLoading => ("media.placeholder.loading", Some(BerylThemeRole::MediaPlaceholder)),
    MediaPlaceholderUnavailable => ("media.placeholder.unavailable", Some(BerylThemeRole::MediaPlaceholder)),
    MediaBorder => ("media.border", Some(BerylThemeRole::MediaPlaceholder)),
    MediaCaption => ("media.caption", Some(BerylThemeRole::MediaPlaceholder)),
    ComposerImageMarker => ("composer.image_marker", Some(BerylThemeRole::InputField)),
    TranscriptImageMarker => ("transcript.image_marker", Some(BerylThemeRole::MarkdownParagraph)),
    FocusRing => ("focus.ring", Some(BerylThemeRole::AppWindow)),
}
