#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BerylThemeProperty {
    Background,
    Border,
    Color,
    Foreground,
    TextBackground,
    FontFamily,
    FontSize,
    FontWeight,
}

impl BerylThemeProperty {
    pub const ALL: &'static [Self] = &[
        Self::Background,
        Self::Border,
        Self::Color,
        Self::Foreground,
        Self::TextBackground,
        Self::FontFamily,
        Self::FontSize,
        Self::FontWeight,
    ];

    pub fn id(self) -> &'static str {
        match self {
            Self::Background => "background",
            Self::Border => "border",
            Self::Color => "color",
            Self::Foreground => "foreground",
            Self::TextBackground => "text_background",
            Self::FontFamily => "font_family",
            Self::FontSize => "font_size",
            Self::FontWeight => "font_weight",
        }
    }
}

macro_rules! define_beryl_theme_roles {
    ($( $variant:ident => ($id:literal, $parent:expr), )+) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum BerylThemeRole {
            $( $variant, )+
        }

        impl BerylThemeRole {
            pub const ALL: &'static [Self] = &[
                $( Self::$variant, )+
            ];

            pub fn id(self) -> &'static str {
                match self {
                    $( Self::$variant => $id, )+
                }
            }

            pub fn static_parent(self) -> Option<Self> {
                match self {
                    $( Self::$variant => $parent, )+
                }
            }
        }

        pub const BUILT_IN_THEME_ROLE_INVENTORY: &[&str] = &[
            $( $id, )+
        ];
    };
}

define_beryl_theme_roles! {
    Root => ("root", None),
    Text => ("text", Some(BerylThemeRole::Root)),
    TextMuted => ("text.muted", Some(BerylThemeRole::Text)),
    TextSubtle => ("text.subtle", Some(BerylThemeRole::Text)),
    TextValue => ("text.value", Some(BerylThemeRole::Text)),
    TextLink => ("text.link", Some(BerylThemeRole::Text)),
    TextCode => ("text.code", Some(BerylThemeRole::Text)),
    TextSemanticInfo => ("text.semantic.info", Some(BerylThemeRole::Text)),
    TextSemanticWarning => ("text.semantic.warning", Some(BerylThemeRole::Text)),
    TextSemanticError => ("text.semantic.error", Some(BerylThemeRole::Text)),
    TextSemanticSuccess => ("text.semantic.success", Some(BerylThemeRole::Text)),
    Surface => ("surface", Some(BerylThemeRole::Root)),
    SurfaceWindow => ("surface.window", Some(BerylThemeRole::Surface)),
    SurfacePanel => ("surface.panel", Some(BerylThemeRole::Surface)),
    SurfaceElevated => ("surface.elevated", Some(BerylThemeRole::Surface)),
    SurfaceInset => ("surface.inset", Some(BerylThemeRole::Surface)),
    SurfaceOverlay => ("surface.overlay", Some(BerylThemeRole::Surface)),
    Primitive => ("primitive", Some(BerylThemeRole::Root)),
    PrimitiveSeparator => ("separator", Some(BerylThemeRole::Primitive)),
    PrimitiveFocusRing => ("focus_ring", Some(BerylThemeRole::Primitive)),
    PrimitiveCaret => ("caret", Some(BerylThemeRole::Primitive)),
    PrimitiveAccentMarker => ("accent_marker", Some(BerylThemeRole::Primitive)),
    PrimitiveResizeHandle => ("resize_handle", Some(BerylThemeRole::Primitive)),
    PrimitiveScrollbarThumb => ("scrollbar.thumb", Some(BerylThemeRole::Primitive)),
    Control => ("control", Some(BerylThemeRole::Root)),
    ControlButton => ("button", Some(BerylThemeRole::Control)),
    ControlButtonLabel => ("button.label", Some(BerylThemeRole::Text)),
    ControlInput => ("input", Some(BerylThemeRole::Control)),
    ControlInputText => ("input.text", Some(BerylThemeRole::Text)),
    ControlSelection => ("selection", Some(BerylThemeRole::InteractionSelected)),
    ControlList => ("list", Some(BerylThemeRole::Control)),
    ControlListHeader => ("list.header", Some(BerylThemeRole::Text)),
    ControlMenu => ("menu", Some(BerylThemeRole::Control)),
    ControlMenuItem => ("menu.item", Some(BerylThemeRole::SurfaceRow)),
    ControlMenuItemLabel => ("menu.item.label", Some(BerylThemeRole::Text)),
    ControlPopup => ("popup", Some(BerylThemeRole::Control)),
    ControlPopupHeader => ("popup.header", Some(BerylThemeRole::Text)),
    ControlNotice => ("notice", Some(BerylThemeRole::Control)),
    ControlNoticeTitle => ("notice.title", Some(BerylThemeRole::Text)),
    ControlNoticeDetail => ("notice.detail", Some(BerylThemeRole::TextSubtle)),
    ControlStatus => ("status", Some(BerylThemeRole::Control)),
    ControlStatusLabel => ("status.label", Some(BerylThemeRole::TextMuted)),
    ControlStatusValue => ("status.value", Some(BerylThemeRole::TextValue)),
    ControlDropdown => ("dropdown", Some(BerylThemeRole::ControlInput)),
    ControlDropdownLabel => ("dropdown.label", Some(BerylThemeRole::Text)),
    ControlColorInput => ("color-input", Some(BerylThemeRole::ControlInput)),
    ControlColorInputLabel => ("color-input.label", Some(BerylThemeRole::Text)),
    ControlColorInputValue => ("color-input.value", Some(BerylThemeRole::TextCode)),
    ControlFilePicker => ("file-picker", Some(BerylThemeRole::ControlInput)),
    ControlFilePickerLabel => ("file-picker.label", Some(BerylThemeRole::Text)),
    ControlTooltip => ("tooltip", Some(BerylThemeRole::ControlPopup)),
    ControlTooltipText => ("tooltip.text", Some(BerylThemeRole::TextSubtle)),
    ControlScrollbar => ("scrollbar", Some(BerylThemeRole::Control)),
    InteractionHover => ("interaction.hover", Some(BerylThemeRole::SurfaceRow)),
    InteractionPressed => ("interaction.pressed", Some(BerylThemeRole::ControlButton)),
    InteractionActive => ("interaction.active", Some(BerylThemeRole::Control)),
    InteractionSelected => ("interaction.selected", Some(BerylThemeRole::SurfaceRow)),
    InteractionFocused => ("interaction.focused", Some(BerylThemeRole::ControlInput)),
    InteractionDisabled => ("interaction.disabled", Some(BerylThemeRole::Control)),
    SemanticInfo => ("semantic.info", Some(BerylThemeRole::ControlNotice)),
    SemanticWarning => ("semantic.warning", Some(BerylThemeRole::ControlNotice)),
    SemanticError => ("semantic.error", Some(BerylThemeRole::ControlNotice)),
    SemanticSuccess => ("semantic.success", Some(BerylThemeRole::ControlNotice)),
    AppWindow => ("app.window", Some(BerylThemeRole::SurfaceWindow)),
    AppWindowTitle => ("app.window.title", Some(BerylThemeRole::TextValue)),
    MainToolbar => ("main.toolbar", Some(BerylThemeRole::SurfaceWindow)),
    MainToolbarTitle => ("main.toolbar.title", Some(BerylThemeRole::TextValue)),
    MainThreadStrip => ("main.thread_strip", Some(BerylThemeRole::SurfaceWindow)),
    MainThreadStripActiveThread => ("main.thread_strip.active_thread", Some(BerylThemeRole::ControlButton)),
    MainThreadStripActiveThreadLabel => ("main.thread_strip.active_thread.label", Some(BerylThemeRole::ControlButtonLabel)),
    MainSeparator => ("main.separator", Some(BerylThemeRole::PrimitiveSeparator)),
    Panel => ("panel", Some(BerylThemeRole::SurfacePanel)),
    SurfaceRow => ("row", Some(BerylThemeRole::Control)),
    ControlRowLabel => ("row.label", Some(BerylThemeRole::Text)),
    SurfaceRowHover => ("row.hover", Some(BerylThemeRole::InteractionHover)),
    SurfaceRowSelected => ("row.selected", Some(BerylThemeRole::InteractionSelected)),
    SurfaceRowDisabled => ("row.disabled", Some(BerylThemeRole::InteractionDisabled)),
    SurfaceRowPending => ("row.pending", Some(BerylThemeRole::SurfaceRow)),
    SurfaceRowUnavailable => ("row.unavailable", Some(BerylThemeRole::InteractionDisabled)),
    SurfaceRowError => ("row.error", Some(BerylThemeRole::SemanticError)),
    SurfaceRowWarning => ("row.warning", Some(BerylThemeRole::SemanticWarning)),
    SurfaceRowInfo => ("row.info", Some(BerylThemeRole::SemanticInfo)),
    SurfaceRowSuccess => ("row.success", Some(BerylThemeRole::SemanticSuccess)),
    StructuralSeparator => ("structural.separator", Some(BerylThemeRole::PrimitiveSeparator)),
    ButtonPrimaryNormal => ("button.primary.normal", Some(BerylThemeRole::ControlButton)),
    ButtonPrimaryHover => ("button.primary.hover", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryPressed => ("button.primary.pressed", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryActive => ("button.primary.active", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryDisabled => ("button.primary.disabled", Some(BerylThemeRole::ButtonPrimaryNormal)),
    ButtonPrimaryLabel => ("button.primary.label", Some(BerylThemeRole::ControlButtonLabel)),
    ButtonSecondaryNormal => ("button.secondary.normal", Some(BerylThemeRole::ControlButton)),
    ButtonSecondaryHover => ("button.secondary.hover", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryPressed => ("button.secondary.pressed", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryActive => ("button.secondary.active", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryDisabled => ("button.secondary.disabled", Some(BerylThemeRole::ButtonSecondaryNormal)),
    ButtonSecondaryLabel => ("button.secondary.label", Some(BerylThemeRole::ControlButtonLabel)),
    InputPanel => ("input.panel", Some(BerylThemeRole::Panel)),
    InputField => ("input.field", Some(BerylThemeRole::ControlInput)),
    InputFieldText => ("input.field.text", Some(BerylThemeRole::ControlInputText)),
    InputFieldFocused => ("input.field.focused", Some(BerylThemeRole::InteractionFocused)),
    InputSelection => ("input.selection", Some(BerylThemeRole::ControlSelection)),
    InputCaret => ("input.caret", Some(BerylThemeRole::PrimitiveCaret)),
    InputError => ("input.error", Some(BerylThemeRole::SemanticError)),
    SettingsWindow => ("settings.window", Some(BerylThemeRole::AppWindow)),
    SettingsSidebar => ("settings.sidebar", Some(BerylThemeRole::ControlList)),
    SettingsSidebarRowNormal => ("settings.sidebar.row.normal", Some(BerylThemeRole::SurfaceRow)),
    SettingsSidebarRowText => ("settings.sidebar.row.text", Some(BerylThemeRole::ControlRowLabel)),
    SettingsSidebarRowHover => ("settings.sidebar.row.hover", Some(BerylThemeRole::SurfaceRowHover)),
    SettingsSidebarRowSelected => ("settings.sidebar.row.selected", Some(BerylThemeRole::SurfaceRowSelected)),
    SettingsPage => ("settings.page", Some(BerylThemeRole::SurfaceWindow)),
    SettingsGroup => ("settings.group", Some(BerylThemeRole::SurfacePanel)),
    SettingsGroupHeaderText => ("settings.group.header.text", Some(BerylThemeRole::ControlListHeader)),
    SettingsRowNormal => ("settings.row.normal", Some(BerylThemeRole::SurfaceRow)),
    SettingsRowLabel => ("settings.row.label", Some(BerylThemeRole::ControlRowLabel)),
    SettingsRowValue => ("settings.row.value", Some(BerylThemeRole::TextValue)),
    SettingsRowHover => ("settings.row.hover", Some(BerylThemeRole::SurfaceRowHover)),
    SettingsRowModified => ("settings.row.modified", Some(BerylThemeRole::SurfaceRowInfo)),
    SettingsRowDisabled => ("settings.row.disabled", Some(BerylThemeRole::SurfaceRowDisabled)),
    SettingsRowDisabledText => ("settings.row.disabled.text", Some(BerylThemeRole::TextMuted)),
    SettingsInputNormal => ("settings.input.normal", Some(BerylThemeRole::ControlInput)),
    SettingsInputText => ("settings.input.text", Some(BerylThemeRole::ControlInputText)),
    SettingsInputFocused => ("settings.input.focused", Some(BerylThemeRole::SettingsInputNormal)),
    SettingsInputError => ("settings.input.error", Some(BerylThemeRole::SettingsInputNormal)),
    SettingsInputSelection => ("settings.input.selection", Some(BerylThemeRole::ControlSelection)),
    SettingsInputCaret => ("settings.input.caret", Some(BerylThemeRole::InputCaret)),
    SettingsPopup => ("settings.popup", Some(BerylThemeRole::PopupSurface)),
    SettingsButtonPrimary => ("settings.button.primary", Some(BerylThemeRole::ButtonPrimaryNormal)),
    SettingsButtonSecondary => ("settings.button.secondary", Some(BerylThemeRole::ButtonSecondaryNormal)),
    SettingsButtonPrimaryLabel => ("settings.button.primary.label", Some(BerylThemeRole::ButtonPrimaryLabel)),
    SettingsButtonSecondaryLabel => ("settings.button.secondary.label", Some(BerylThemeRole::ButtonSecondaryLabel)),
    TranscriptShell => ("transcript.shell", Some(BerylThemeRole::SurfacePanel)),
    TranscriptAssistantFinal => ("transcript.turn.assistant.final", Some(BerylThemeRole::Text)),
    TranscriptAssistantCommentary => ("transcript.turn.assistant.commentary", Some(BerylThemeRole::TranscriptAssistantFinal)),
    TranscriptAssistantReasoning => ("transcript.turn.assistant.reasoning", Some(BerylThemeRole::TextSubtle)),
    TranscriptUserInput => ("transcript.turn.user", Some(BerylThemeRole::SurfacePanel)),
    TranscriptUserInputText => ("transcript.turn.user.text", Some(BerylThemeRole::Text)),
    TranscriptActivityCaret => ("transcript.activity_caret", Some(BerylThemeRole::PrimitiveCaret)),
    TranscriptSelection => ("transcript.selection", Some(BerylThemeRole::ControlSelection)),
    TranscriptQuotePopup => ("transcript.quote_popup", Some(BerylThemeRole::PopupSurface)),
    TranscriptQuotePopupText => ("transcript.quote_popup.text", Some(BerylThemeRole::ControlButtonLabel)),
    TranscriptContextMenu => ("transcript.context_menu", Some(BerylThemeRole::PopupSurface)),
    TranscriptContextMenuHeaderText => ("transcript.context_menu.header.text", Some(BerylThemeRole::ControlPopupHeader)),
    TranscriptPending => ("transcript.pending", Some(BerylThemeRole::TranscriptShell)),
    TranscriptUnavailable => ("transcript.unavailable", Some(BerylThemeRole::TranscriptShell)),
    MarkdownParagraph => ("markdown.paragraph", Some(BerylThemeRole::Text)),
    MarkdownHeading => ("markdown.heading", Some(BerylThemeRole::TextValue)),
    MarkdownEmphasis => ("markdown.emphasis", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownStrongEmphasis => ("markdown.strong_emphasis", Some(BerylThemeRole::MarkdownParagraph)),
    MarkdownInlineCode => ("markdown.inline_code", Some(BerylThemeRole::TextCode)),
    MarkdownLink => ("markdown.link", Some(BerylThemeRole::TextLink)),
    MarkdownBlockQuote => ("markdown.block_quote", Some(BerylThemeRole::PrimitiveSeparator)),
    MarkdownListMarker => ("markdown.list_marker", Some(BerylThemeRole::TextMuted)),
    MarkdownThematicBreak => ("markdown.thematic_break", Some(BerylThemeRole::PrimitiveSeparator)),
    MarkdownUnsupportedFallback => ("markdown.unsupported_fallback", Some(BerylThemeRole::TextCode)),
    CodePanelContainer => ("code_panel.container", Some(BerylThemeRole::SurfaceInset)),
    CodePanelHeader => ("code_panel.header", Some(BerylThemeRole::SurfaceInset)),
    CodePanelHeaderText => ("code_panel.header.text", Some(BerylThemeRole::TextCode)),
    CodePanelBody => ("code_panel.body", Some(BerylThemeRole::SurfaceInset)),
    CodePanelBodyText => ("code_panel.body.text", Some(BerylThemeRole::TextCode)),
    CodePanelBorder => ("code_panel.border", Some(BerylThemeRole::PrimitiveSeparator)),
    CodePanelSelection => ("code_panel.selection", Some(BerylThemeRole::ControlSelection)),
    CodePanelResizeHandle => ("code_panel.resize_handle", Some(BerylThemeRole::PrimitiveResizeHandle)),
    CodePanelButtonNormal => ("code_panel.button.normal", Some(BerylThemeRole::ButtonSecondaryNormal)),
    CodePanelButtonHover => ("code_panel.button.hover", Some(BerylThemeRole::CodePanelButtonNormal)),
    CodePanelButtonActive => ("code_panel.button.active", Some(BerylThemeRole::CodePanelButtonNormal)),
    CodePanelButtonDisabled => ("code_panel.button.disabled", Some(BerylThemeRole::CodePanelButtonNormal)),
    SyntaxMarkupHeadingMarker => ("syntax.markup.heading_marker", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupQuoteMarker => ("syntax.markup.quote_marker", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupListMarker => ("syntax.markup.list_marker", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupThematicBreak => ("syntax.markup.thematic_break", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupFenceDelimiter => ("syntax.markup.fence_delimiter", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupFenceInfo => ("syntax.markup.fence_info", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupCodeBlock => ("syntax.markup.code_block", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupCodeSpanDelimiter => ("syntax.markup.code_span_delimiter", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupCodeSpan => ("syntax.markup.code_span", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupEmphasisDelimiter => ("syntax.markup.emphasis_delimiter", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupStrongDelimiter => ("syntax.markup.strong_delimiter", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupLinkText => ("syntax.markup.link_text", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupLinkDestination => ("syntax.markup.link_destination", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupImageMarker => ("syntax.markup.image_marker", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupPunctuation => ("syntax.markup.punctuation", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxMarkupHtml => ("syntax.markup.html", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxEscape => ("syntax.escape", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxStructuralPunctuation => ("syntax.structural_punctuation", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxKey => ("syntax.key", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxString => ("syntax.string", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxNumber => ("syntax.number", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxBoolean => ("syntax.boolean", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxNull => ("syntax.null", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxDateTime => ("syntax.date_time", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxComment => ("syntax.comment", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxSectionHeader => ("syntax.section_header", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxAssignment => ("syntax.assignment", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxTokenEscape => ("syntax.token_escape", Some(BerylThemeRole::CodePanelBodyText)),
    SyntaxError => ("syntax.error", Some(BerylThemeRole::CodePanelBodyText)),
    GraphOverlay => ("graph.overlay", Some(BerylThemeRole::SurfacePanel)),
    GraphColumn => ("graph.column", Some(BerylThemeRole::ColumnSelectorColumn)),
    GraphColumnHeader => ("graph.column_header", Some(BerylThemeRole::ColumnSelectorHeader)),
    GraphColumnHeaderText => ("graph.column_header.text", Some(BerylThemeRole::ColumnSelectorHeaderText)),
    GraphRowTopic => ("graph.row.topic", Some(BerylThemeRole::ColumnSelectorRow)),
    GraphRowTopicText => ("graph.row.topic.text", Some(BerylThemeRole::ControlRowLabel)),
    GraphRowChecklist => ("graph.row.checklist", Some(BerylThemeRole::ColumnSelectorRow)),
    GraphRowChecklistText => ("graph.row.checklist.text", Some(BerylThemeRole::ControlRowLabel)),
    GraphRowChecklistItem => ("graph.row.checklist_item", Some(BerylThemeRole::ColumnSelectorRow)),
    GraphRowChecklistItemText => ("graph.row.checklist_item.text", Some(BerylThemeRole::ControlRowLabel)),
    GraphRowThreadRef => ("graph.row.thread_ref", Some(BerylThemeRole::ColumnSelectorRow)),
    GraphRowThreadRefText => ("graph.row.thread_ref.text", Some(BerylThemeRole::TextLink)),
    GraphRowThreadRefMeta => ("graph.row.thread_ref.meta", Some(BerylThemeRole::TextMuted)),
    GraphRowSoftLink => ("graph.row.soft_link", Some(BerylThemeRole::ColumnSelectorRow)),
    GraphRowSoftLinkText => ("graph.row.soft_link.text", Some(BerylThemeRole::MarkdownEmphasis)),
    GraphRowHover => ("graph.row.hover", Some(BerylThemeRole::SurfaceRowHover)),
    GraphRowSelected => ("graph.row.selected", Some(BerylThemeRole::ColumnSelectorRowSelected)),
    GraphRowSelectedText => ("graph.row.selected.text", Some(BerylThemeRole::GraphRowTopicText)),
    GraphRowPending => ("graph.row.pending", Some(BerylThemeRole::SurfaceRowPending)),
    GraphRowPendingText => ("graph.row.pending.text", Some(BerylThemeRole::TextMuted)),
    GraphRowDisabled => ("graph.row.disabled", Some(BerylThemeRole::SurfaceRowDisabled)),
    GraphRowDisabledText => ("graph.row.disabled.text", Some(BerylThemeRole::TextMuted)),
    GraphRowInvalid => ("graph.row.invalid", Some(BerylThemeRole::SurfaceRowUnavailable)),
    GraphRowInvalidText => ("graph.row.invalid.text", Some(BerylThemeRole::TextSemanticWarning)),
    GraphRowError => ("graph.row.error", Some(BerylThemeRole::SurfaceRowError)),
    GraphRowErrorText => ("graph.row.error.text", Some(BerylThemeRole::TextSemanticError)),
    ChecklistSidebar => ("checklist.sidebar", Some(BerylThemeRole::SurfacePanel)),
    ChecklistHeader => ("checklist.header", Some(BerylThemeRole::ControlListHeader)),
    ChecklistRow => ("checklist.row", Some(BerylThemeRole::SurfaceRow)),
    ChecklistRowNumberText => ("checklist.row.number.text", Some(BerylThemeRole::TextMuted)),
    ChecklistRowText => ("checklist.row.text", Some(BerylThemeRole::ControlRowLabel)),
    ChecklistStatusTodo => ("checklist.status.todo", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ChecklistStatusTodoText => ("checklist.status.todo.text", Some(BerylThemeRole::TextMuted)),
    ChecklistStatusInProgress => ("checklist.status.in_progress", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ChecklistStatusInProgressText => ("checklist.status.in_progress.text", Some(BerylThemeRole::TextSemanticWarning)),
    ChecklistStatusDone => ("checklist.status.done", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ChecklistStatusDoneText => ("checklist.status.done.text", Some(BerylThemeRole::TextSemanticSuccess)),
    ThreadSelectorSurface => ("thread_selector.surface", Some(BerylThemeRole::PopupSurface)),
    ThreadSelectorHeaderText => ("thread_selector.header.text", Some(BerylThemeRole::ControlPopupHeader)),
    ThreadSelectorColumn => ("thread_selector.column", Some(BerylThemeRole::ColumnSelectorColumn)),
    ThreadSelectorColumnHeader => ("thread_selector.column.header", Some(BerylThemeRole::ColumnSelectorHeader)),
    ThreadSelectorColumnHeaderText => ("thread_selector.column.header.text", Some(BerylThemeRole::ControlListHeader)),
    ThreadSelectorRow => ("thread_selector.row", Some(BerylThemeRole::ColumnSelectorRow)),
    ThreadSelectorRowLabel => ("thread_selector.row.label", Some(BerylThemeRole::ControlRowLabel)),
    ThreadSelectorRowMeta => ("thread_selector.row.meta", Some(BerylThemeRole::TextMuted)),
    ThreadSelectorRowSelected => ("thread_selector.row.selected", Some(BerylThemeRole::ColumnSelectorRowSelected)),
    ThreadSelectorRowSelectedText => ("thread_selector.row.selected.text", Some(BerylThemeRole::ThreadSelectorRowLabel)),
    ThreadSelectorRowActive => ("thread_selector.row.active", Some(BerylThemeRole::ThreadSelectorRowSelected)),
    ThreadSelectorRowActiveText => ("thread_selector.row.active.text", Some(BerylThemeRole::ThreadSelectorRowSelectedText)),
    ThreadSelectorRowUnavailable => ("thread_selector.row.unavailable", Some(BerylThemeRole::SurfaceRowDisabled)),
    ThreadSelectorRowUnavailableText => ("thread_selector.row.unavailable.text", Some(BerylThemeRole::TextMuted)),
    WorkspacePickerSurface => ("workspace_picker.surface", Some(BerylThemeRole::PopupSurface)),
    WorkspacePickerHeaderText => ("workspace_picker.header.text", Some(BerylThemeRole::ControlPopupHeader)),
    WorkspacePickerHeaderDetail => ("workspace_picker.header.detail", Some(BerylThemeRole::ControlNoticeDetail)),
    WorkspacePickerWorkspaceRow => ("workspace_picker.workspace_row", Some(BerylThemeRole::SurfaceRow)),
    WorkspacePickerWorkspaceRowTitle => ("workspace_picker.workspace_row.title", Some(BerylThemeRole::ControlRowLabel)),
    WorkspacePickerWorkspaceRowPath => ("workspace_picker.workspace_row.path", Some(BerylThemeRole::TextCode)),
    WorkspacePickerMemberRow => ("workspace_picker.member_row", Some(BerylThemeRole::SurfaceRow)),
    WorkspacePickerMemberRowTitle => ("workspace_picker.member_row.title", Some(BerylThemeRole::ControlRowLabel)),
    WorkspacePickerMemberRowPath => ("workspace_picker.member_row.path", Some(BerylThemeRole::TextCode)),
    WorkspacePickerRuntimeRow => ("workspace_picker.runtime_row", Some(BerylThemeRole::ControlMenuItem)),
    WorkspacePickerRuntimeRowText => ("workspace_picker.runtime_row.text", Some(BerylThemeRole::ControlMenuItemLabel)),
    WorkspacePickerUnavailableText => ("workspace_picker.unavailable.text", Some(BerylThemeRole::TextMuted)),
    WorkspacePickerRowActive => ("workspace_picker.row.active", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ColumnSelectorColumn => ("column_selector.column", Some(BerylThemeRole::ControlList)),
    ColumnSelectorHeader => ("column_selector.header", Some(BerylThemeRole::ColumnSelectorColumn)),
    ColumnSelectorHeaderText => ("column_selector.header.text", Some(BerylThemeRole::ControlListHeader)),
    ColumnSelectorRow => ("column_selector.row", Some(BerylThemeRole::SurfaceRow)),
    ColumnSelectorRowSelected => ("column_selector.row.selected", Some(BerylThemeRole::SurfaceRowSelected)),
    ColumnSelectorAccent => ("column_selector.accent", Some(BerylThemeRole::PrimitiveAccentMarker)),
    PopupSurface => ("popup.surface", Some(BerylThemeRole::ControlPopup)),
    PopupRowNormal => ("popup.row.normal", Some(BerylThemeRole::PopupSurface)),
    PopupRowHover => ("popup.row.hover", Some(BerylThemeRole::PopupRowNormal)),
    PopupRowSelected => ("popup.row.selected", Some(BerylThemeRole::PopupRowNormal)),
    PopupRowDisabled => ("popup.row.disabled", Some(BerylThemeRole::PopupRowNormal)),
    OverlayBackdrop => ("overlay.backdrop", Some(BerylThemeRole::AppWindow)),
    NoticeInfo => ("notice.info", Some(BerylThemeRole::PopupSurface)),
    NoticeWarning => ("notice.warning", Some(BerylThemeRole::PopupSurface)),
    NoticeError => ("notice.error", Some(BerylThemeRole::PopupSurface)),
    NoticeSuccess => ("notice.success", Some(BerylThemeRole::PopupSurface)),
    DiagnosticSurface => ("diagnostic.surface", Some(BerylThemeRole::Panel)),
    DiagnosticRow => ("diagnostic.row", Some(BerylThemeRole::DiagnosticSurface)),
    DiagnosticError => ("diagnostic.error", Some(BerylThemeRole::DiagnosticRow)),
    DiagnosticWarning => ("diagnostic.warning", Some(BerylThemeRole::DiagnosticRow)),
    StatusLine => ("status.line", Some(BerylThemeRole::AppWindow)),
    StatusLineCell => ("status.line.cell", Some(BerylThemeRole::ControlStatus)),
    StatusLineLabel => ("status.line.label", Some(BerylThemeRole::ControlStatusLabel)),
    StatusLineValue => ("status.line.value", Some(BerylThemeRole::ControlStatusValue)),
    StatusValueWorking => ("status.value.working", Some(BerylThemeRole::StatusLineValue)),
    StatusValueCompacting => ("status.value.compacting", Some(BerylThemeRole::StatusLineValue)),
    StatusValueOk => ("status.value.ok", Some(BerylThemeRole::StatusLineValue)),
    StatusValueError => ("status.value.error", Some(BerylThemeRole::StatusLineValue)),
    StatusValuePending => ("status.value.pending", Some(BerylThemeRole::StatusLineValue)),
    StatusValueUnavailable => ("status.value.unavailable", Some(BerylThemeRole::StatusLineValue)),
    StatusValueStreaming => ("status.value.streaming", Some(BerylThemeRole::StatusLineValue)),
    ActivityPanel => ("activity.panel", Some(BerylThemeRole::StatusLine)),
    ActivityRow => ("activity.row", Some(BerylThemeRole::StatusLineCell)),
    ActivityLabel => ("activity.label", Some(BerylThemeRole::StatusLineLabel)),
    ActivityValue => ("activity.value", Some(BerylThemeRole::StatusLineValue)),
    ActivityIndicatorRunning => ("activity.indicator.running", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ActivityIndicatorOk => ("activity.indicator.ok", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ActivityIndicatorError => ("activity.indicator.error", Some(BerylThemeRole::PrimitiveAccentMarker)),
    ActivityResizeHandle => ("activity.resize_handle", Some(BerylThemeRole::PrimitiveResizeHandle)),
    ScrollbarThumbNormal => ("scrollbar.thumb.normal", Some(BerylThemeRole::PrimitiveScrollbarThumb)),
    ScrollbarThumbHover => ("scrollbar.thumb.hover", Some(BerylThemeRole::PrimitiveScrollbarThumb)),
    ScrollbarThumbDragging => ("scrollbar.thumb.dragging", Some(BerylThemeRole::PrimitiveScrollbarThumb)),
    MediaPlaceholder => ("media.placeholder", Some(BerylThemeRole::TranscriptShell)),
    MediaPlaceholderText => ("media.placeholder.text", Some(BerylThemeRole::TextMuted)),
    MediaPlaceholderLoading => ("media.placeholder.loading", Some(BerylThemeRole::MediaPlaceholder)),
    MediaPlaceholderLoadingText => ("media.placeholder.loading.text", Some(BerylThemeRole::MediaPlaceholderText)),
    MediaPlaceholderUnavailable => ("media.placeholder.unavailable", Some(BerylThemeRole::MediaPlaceholder)),
    MediaPlaceholderUnavailableText => ("media.placeholder.unavailable.text", Some(BerylThemeRole::TextSemanticWarning)),
    MediaBorder => ("media.border", Some(BerylThemeRole::MediaPlaceholder)),
    MediaCaption => ("media.caption", Some(BerylThemeRole::MediaPlaceholderText)),
    ComposerImageMarker => ("composer.image_marker", Some(BerylThemeRole::InputField)),
    TranscriptImageMarker => ("transcript.image_marker", Some(BerylThemeRole::MarkdownParagraph)),
    FocusRing => ("focus.ring", Some(BerylThemeRole::PrimitiveFocusRing)),
}
