use beryl_model::{
    AssetId, ProjectionRevision, SyndicItemId, SyndicProjectionId, SyndicResourceId,
};

use crate::{ProjectionTextSource, ResourceOrdinal, SyndicRecordError};

use super::super::{MAX_MEDIA_TYPE_BYTES, validate_text};
use super::ProjectionSourceRange;

/// Closed heavy-resource classification retained as bounded metadata.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceKind {
    Code,
    Table,
    Image,
    Attachment,
    Log,
    Other,
}

/// V1 textual resource backing without duplicated heavy bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceBacking {
    TextRange {
        source: ProjectionTextSource,
        range: ProjectionSourceRange,
    },
    GeneratedMedia(GeneratedMediaResourceDisposition),
}

/// Durable owned-byte availability of one provider-completed generated-media resource.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedMediaResourceDisposition {
    PendingAsset,
    Asset(AssetId),
    Unavailable(GeneratedMediaUnavailableReason),
}

/// Why generated bytes could not become Beryl-owned asset authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedMediaUnavailableReason {
    Missing,
    Changed,
    Oversized,
    Unsupported,
    Unreadable,
}

impl ResourceBacking {
    #[must_use]
    pub const fn text_source(self) -> Option<ProjectionTextSource> {
        match self {
            Self::TextRange { source, .. } => Some(source),
            Self::GeneratedMedia(_) => None,
        }
    }

    #[must_use]
    pub const fn range(self) -> Option<ProjectionSourceRange> {
        match self {
            Self::TextRange { range, .. } => Some(range),
            Self::GeneratedMedia(_) => None,
        }
    }
}

/// Bounded structural metadata used without loading resource bytes.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ResourceStructure {
    Code {
        language: Option<Box<str>>,
        logical_lines: u64,
    },
    Table {
        body_rows: u64,
        columns: u64,
        header_range: ProjectionSourceRange,
    },
    Opaque,
}

impl ResourceStructure {
    pub fn code(language: Option<&str>, logical_lines: u64) -> Result<Self, SyndicRecordError> {
        Ok(Self::Code {
            language: language
                .map(|value| validate_text("code language", value, 256, false))
                .transpose()?,
            logical_lines,
        })
    }

    pub fn table(
        body_rows: u64,
        columns: u64,
        header_range: ProjectionSourceRange,
    ) -> Result<Self, SyndicRecordError> {
        if columns == 0 {
            return Err(SyndicRecordError::ZeroValue {
                kind: "table column count",
            });
        }
        Ok(Self::Table {
            body_rows,
            columns,
            header_range,
        })
    }
}

/// Range-readable resource metadata without loading its backing bytes.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResourceMetadataRecord {
    id: SyndicResourceId,
    revision: ProjectionRevision,
    projection_id: Option<SyndicProjectionId>,
    item_id: SyndicItemId,
    ordinal: Option<ResourceOrdinal>,
    kind: ResourceKind,
    media_type: Option<Box<str>>,
    backing: ResourceBacking,
    byte_length: Option<u64>,
    digest: Option<[u8; 32]>,
    preview_range: Option<ProjectionSourceRange>,
    structure: ResourceStructure,
}

impl ResourceMetadataRecord {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: SyndicResourceId,
        revision: ProjectionRevision,
        projection_id: SyndicProjectionId,
        item_id: SyndicItemId,
        ordinal: ResourceOrdinal,
        kind: ResourceKind,
        media_type: impl AsRef<str>,
        backing: ResourceBacking,
        digest: [u8; 32],
        preview_range: Option<ProjectionSourceRange>,
        structure: ResourceStructure,
    ) -> Result<Self, SyndicRecordError> {
        let Some(range) = backing.range() else {
            return Err(SyndicRecordError::InvalidResourceStructure);
        };
        let byte_length = range.len();
        if let Some(preview) = preview_range
            && preview.end() > byte_length
        {
            return Err(SyndicRecordError::InvalidResourcePreviewRange {
                resource_bytes: byte_length,
                preview_start: preview.start(),
                preview_end: preview.end(),
            });
        }
        let valid_structure = matches!(
            (kind, &structure),
            (ResourceKind::Code, ResourceStructure::Code { .. })
                | (ResourceKind::Table, ResourceStructure::Table { .. })
                | (
                    ResourceKind::Image
                        | ResourceKind::Attachment
                        | ResourceKind::Log
                        | ResourceKind::Other,
                    ResourceStructure::Opaque
                )
        );
        if !valid_structure {
            return Err(SyndicRecordError::InvalidResourceStructure);
        }
        if let ResourceStructure::Table { header_range, .. } = &structure
            && header_range.end() > byte_length
        {
            return Err(SyndicRecordError::InvalidResourceStructure);
        }
        Ok(Self {
            id,
            revision,
            projection_id: Some(projection_id),
            item_id,
            ordinal: Some(ordinal),
            kind,
            media_type: Some(validate_text(
                "resource media type",
                media_type.as_ref(),
                MAX_MEDIA_TYPE_BYTES,
                false,
            )?),
            backing,
            byte_length: Some(byte_length),
            digest: Some(digest),
            preview_range,
            structure,
        })
    }

    /// Creates one path-free pending resource for a completed standalone generated-media item.
    #[must_use]
    pub const fn pending_generated_media(
        id: SyndicResourceId,
        revision: ProjectionRevision,
        item_id: SyndicItemId,
    ) -> Self {
        Self::generated_media(
            id,
            revision,
            item_id,
            GeneratedMediaResourceDisposition::PendingAsset,
        )
    }

    #[must_use]
    pub const fn generated_media(
        id: SyndicResourceId,
        revision: ProjectionRevision,
        item_id: SyndicItemId,
        disposition: GeneratedMediaResourceDisposition,
    ) -> Self {
        let (byte_length, digest) = match disposition {
            GeneratedMediaResourceDisposition::Asset(asset) => {
                (Some(asset.length().get()), Some(asset.digest()))
            }
            GeneratedMediaResourceDisposition::PendingAsset
            | GeneratedMediaResourceDisposition::Unavailable(_) => (None, None),
        };
        Self {
            id,
            revision,
            projection_id: None,
            item_id,
            ordinal: None,
            kind: ResourceKind::Image,
            media_type: None,
            backing: ResourceBacking::GeneratedMedia(disposition),
            byte_length,
            digest,
            preview_range: None,
            structure: ResourceStructure::Opaque,
        }
    }

    #[must_use]
    pub const fn id(&self) -> SyndicResourceId {
        self.id
    }
    #[must_use]
    pub const fn revision(&self) -> ProjectionRevision {
        self.revision
    }
    #[must_use]
    pub const fn projection_id(&self) -> Option<SyndicProjectionId> {
        self.projection_id
    }
    #[must_use]
    pub const fn item_id(&self) -> SyndicItemId {
        self.item_id
    }
    #[must_use]
    pub const fn ordinal(&self) -> Option<ResourceOrdinal> {
        self.ordinal
    }
    #[must_use]
    pub const fn kind(&self) -> ResourceKind {
        self.kind
    }
    #[must_use]
    pub fn media_type(&self) -> Option<&str> {
        self.media_type.as_deref()
    }
    #[must_use]
    pub const fn backing(&self) -> ResourceBacking {
        self.backing
    }
    #[must_use]
    pub const fn byte_length(&self) -> Option<u64> {
        self.byte_length
    }
    #[must_use]
    pub const fn digest(&self) -> Option<&[u8; 32]> {
        self.digest.as_ref()
    }
    #[must_use]
    pub const fn preview_range(&self) -> Option<ProjectionSourceRange> {
        self.preview_range
    }
    #[must_use]
    pub const fn structure(&self) -> &ResourceStructure {
        &self.structure
    }
}
