use beryl_model::{
    CasItemId, CasThreadId, CasTurnId, SyndicItemId, SyndicPathDigest, SyndicProjectionId,
    SyndicThreadId, SyndicTurnId,
};

use super::*;

pub(super) struct ItemRecordFacts {
    pub(super) item: SyndicItemId,
    pub(super) turn: SyndicTurnId,
    pub(super) active_item_revision: ProjectionRevision,
    pub(super) active_source: CasItemSource,
    pub(super) active_canonical: SealedProviderFrameReference,
    pub(super) cas_thread: CasThreadId,
    pub(super) cas_turn: CasTurnId,
    pub(super) cas_item: CasItemId,
    pub(super) projection_record: ProjectionRecord,
    pub(super) projection: SyndicProjectionId,
    pub(super) projection_revision: ProjectionRevision,
    pub(super) generation: ItemProjectionGeneration,
    pub(super) active_text_source: ProjectionTextSource,
    pub(super) active_projection_digest: [u8; 32],
    pub(super) suffix_item: SyndicItemId,
    pub(super) suffix_source: CasItemSource,
    pub(super) suffix_canonical: SealedProviderFrameReference,
    pub(super) suffix_cas_item: CasItemId,
    pub(super) suffix_projection_record: ProjectionRecord,
    pub(super) suffix_projection: SyndicProjectionId,
    pub(super) suffix_text_source: ProjectionTextSource,
    pub(super) digest_seed: [u8; 32],
    pub(super) suffix_projection_digest: [u8; 32],
    pub(super) build_item: SyndicItemId,
    pub(super) build_source: CasItemSource,
    pub(super) build_canonical: SealedProviderFrameReference,
    pub(super) build_cas_item: CasItemId,
    pub(super) build_text_source: ProjectionTextSource,
    pub(super) activity_item: SyndicItemId,
    pub(super) activity_source: CasItemSource,
    pub(super) activity_canonical: SealedProviderFrameReference,
    pub(super) activity_cas_item: CasItemId,
    pub(super) activity_entry: ActivityQueryEntryRecord,
    pub(super) thread: SyndicThreadId,
    pub(super) digest: SyndicPathDigest,
    pub(super) thread_revision: ThreadRevision,
    pub(super) transcript_digest: [u8; 32],
}

pub(super) fn records(facts: ItemRecordFacts) -> Vec<FixtureRecord> {
    let ItemRecordFacts {
        item,
        turn,
        active_item_revision,
        active_source,
        active_canonical,
        cas_thread,
        cas_turn,
        cas_item,
        projection_record,
        projection,
        projection_revision,
        generation,
        active_text_source,
        active_projection_digest,
        suffix_item,
        suffix_source,
        suffix_canonical,
        suffix_cas_item,
        suffix_projection_record,
        suffix_projection,
        suffix_text_source,
        digest_seed,
        suffix_projection_digest,
        build_item,
        build_source,
        build_canonical,
        build_cas_item,
        build_text_source,
        activity_item,
        activity_source,
        activity_canonical,
        activity_cas_item,
        activity_entry,
        thread,
        digest,
        thread_revision,
        transcript_digest,
    } = facts;

    vec![
        FixtureRecord::CanonicalItem(
            CanonicalItemRecord::with_provider_state(
                item,
                turn,
                TurnItemOrdinal::FIRST,
                active_item_revision,
                SourceEventSequence::new(3).unwrap(),
                3,
                active_source,
                Some(AssistantMessagePhase::Commentary),
                active_canonical,
                Some(ProviderNarrativeCompletionDisposition::Equal),
                CanonicalItemPresentation::Narrative,
            )
            .unwrap(),
        ),
        FixtureRecord::TurnItem(TurnItemIndexRecord::new(
            turn,
            TurnItemOrdinal::FIRST,
            item,
            active_item_revision,
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            item,
            ItemSourceEventOrdinal::FIRST,
            turn,
            SourceEventSequence::FIRST,
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            item,
            ItemSourceEventOrdinal::new(2).unwrap(),
            turn,
            SourceEventSequence::new(2).unwrap(),
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            item,
            ItemSourceEventOrdinal::new(3).unwrap(),
            turn,
            SourceEventSequence::new(3).unwrap(),
        )),
        FixtureRecord::CasItem(CasItemIndexRecord::new(
            cas_thread.clone(),
            cas_turn.clone(),
            cas_item,
            item,
            active_item_revision,
        )),
        FixtureRecord::Projection(projection_record),
        FixtureRecord::StableItemProjection(StableItemProjectionIndexRecord::new(
            item,
            ProjectionOrdinal::FIRST,
            projection,
            projection_revision,
        )),
        FixtureRecord::ItemProjectionSet(ItemProjectionSetRecord::new(
            item,
            generation,
            ProjectionFormatVersion::V1,
            active_item_revision,
            active_text_source,
            6,
            1,
            0,
            active_projection_digest,
            1,
            0,
            active_projection_digest,
            MarkdownParserCheckpoint::new(
                6,
                6,
                ProjectionTextSourceCursor::ProviderNarrative { logical_start: 6 },
                6,
                Box::<str>::default(),
                false,
                None,
            ),
            true,
        )),
        FixtureRecord::ItemProjectionHead(ItemProjectionHeadRecord::new(
            item,
            projection_revision,
            active_item_revision,
            generation,
            ProjectionLifecycle::Current,
        )),
        FixtureRecord::CanonicalItem(
            CanonicalItemRecord::with_provider_state(
                suffix_item,
                turn,
                TurnItemOrdinal::new(2).unwrap(),
                projection_revision,
                SourceEventSequence::new(4).unwrap(),
                1,
                suffix_source,
                Some(AssistantMessagePhase::Commentary),
                suffix_canonical,
                None,
                CanonicalItemPresentation::Narrative,
            )
            .unwrap(),
        ),
        FixtureRecord::TurnItem(TurnItemIndexRecord::new(
            turn,
            TurnItemOrdinal::new(2).unwrap(),
            suffix_item,
            projection_revision,
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            suffix_item,
            ItemSourceEventOrdinal::FIRST,
            turn,
            SourceEventSequence::new(4).unwrap(),
        )),
        FixtureRecord::CasItem(CasItemIndexRecord::new(
            cas_thread.clone(),
            cas_turn.clone(),
            suffix_cas_item,
            suffix_item,
            projection_revision,
        )),
        FixtureRecord::Projection(suffix_projection_record),
        FixtureRecord::ItemProjection(ItemProjectionIndexRecord::new(
            suffix_item,
            generation,
            ProjectionOrdinal::FIRST,
            suffix_projection,
            projection_revision,
        )),
        FixtureRecord::ItemProjectionSet(ItemProjectionSetRecord::new(
            suffix_item,
            generation,
            ProjectionFormatVersion::V1,
            projection_revision,
            suffix_text_source,
            0,
            0,
            0,
            digest_seed,
            1,
            0,
            suffix_projection_digest,
            MarkdownParserCheckpoint::new(
                0,
                0,
                ProjectionTextSourceCursor::ProviderNarrative { logical_start: 0 },
                0,
                Box::<str>::default(),
                false,
                None,
            ),
            false,
        )),
        FixtureRecord::ItemProjectionHead(ItemProjectionHeadRecord::new(
            suffix_item,
            projection_revision,
            projection_revision,
            generation,
            ProjectionLifecycle::Current,
        )),
        FixtureRecord::CanonicalItem(
            CanonicalItemRecord::with_provider_state(
                build_item,
                turn,
                TurnItemOrdinal::new(3).unwrap(),
                projection_revision,
                SourceEventSequence::new(5).unwrap(),
                1,
                build_source,
                Some(AssistantMessagePhase::Commentary),
                build_canonical,
                None,
                CanonicalItemPresentation::Narrative,
            )
            .unwrap(),
        ),
        FixtureRecord::TurnItem(TurnItemIndexRecord::new(
            turn,
            TurnItemOrdinal::new(3).unwrap(),
            build_item,
            projection_revision,
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            build_item,
            ItemSourceEventOrdinal::FIRST,
            turn,
            SourceEventSequence::new(5).unwrap(),
        )),
        FixtureRecord::CasItem(CasItemIndexRecord::new(
            cas_thread.clone(),
            cas_turn.clone(),
            build_cas_item,
            build_item,
            projection_revision,
        )),
        FixtureRecord::ItemProjectionBuild(ItemProjectionBuildRecord::new(
            build_item,
            generation,
            projection_revision,
            ProjectionFormatVersion::V1,
            projection_revision,
            build_text_source,
            0,
            0,
            0,
            digest_seed,
            ItemProjectionBuildPhase::Parsing(MarkdownParserCheckpoint::new(
                0,
                0,
                ProjectionTextSourceCursor::ProviderNarrative { logical_start: 0 },
                0,
                Box::<str>::default(),
                false,
                None,
            )),
        )),
        FixtureRecord::CanonicalItem(
            CanonicalItemRecord::with_provider_state(
                activity_item,
                turn,
                TurnItemOrdinal::new(4).unwrap(),
                ProjectionRevision::new(2).unwrap(),
                SourceEventSequence::new(7).unwrap(),
                2,
                activity_source,
                None,
                activity_canonical,
                None,
                CanonicalItemPresentation::Operational,
            )
            .unwrap(),
        ),
        FixtureRecord::TurnItem(TurnItemIndexRecord::new(
            turn,
            TurnItemOrdinal::new(4).unwrap(),
            activity_item,
            ProjectionRevision::new(2).unwrap(),
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            activity_item,
            ItemSourceEventOrdinal::FIRST,
            turn,
            SourceEventSequence::new(6).unwrap(),
        )),
        FixtureRecord::ItemSourceEvent(ItemSourceEventIndexRecord::new(
            activity_item,
            ItemSourceEventOrdinal::new(2).unwrap(),
            turn,
            SourceEventSequence::new(7).unwrap(),
        )),
        FixtureRecord::CasItem(CasItemIndexRecord::new(
            cas_thread,
            cas_turn,
            activity_cas_item,
            activity_item,
            ProjectionRevision::new(2).unwrap(),
        )),
        FixtureRecord::ActivityQueryEntry(activity_entry),
        FixtureRecord::TranscriptViewHead(TranscriptViewHeadRecord::new(
            thread,
            TranscriptGeneration::FIRST,
            projection_revision,
            0,
            Some(turn),
            digest,
            ProjectionLifecycle::Current,
        )),
        FixtureRecord::TranscriptBuild(TranscriptBuildRecord::new(
            thread,
            TranscriptGeneration::FIRST,
            projection_revision,
            thread_revision,
            Some(turn),
            digest,
            1,
            0,
            transcript_digest,
            false,
            TranscriptBuildPhase::Complete,
        )),
        FixtureRecord::TranscriptPathTurn(TranscriptPathTurnRecord::new(
            thread,
            TranscriptGeneration::FIRST,
            TurnDepth::FIRST,
            turn,
            digest,
            TurnStateRevision::FIRST,
            TurnLifecycle::Active,
            7,
            4,
            0,
            timestamp(8),
        )),
        FixtureRecord::HistorySummary(HistorySummaryRecord::new(
            thread,
            projection_revision,
            thread_revision,
            Some(turn),
            digest,
            false,
            timestamp(8),
        )),
    ]
}
