[package]
name = "beryl-state"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-faults = []

[dependencies]
beryl-home-store.workspace = true
beryl-model.workspace = true
sha2.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
beryl-home-store = { workspace = true, features = ["test-faults"] }
tempfile.workspace = true
