use std::{error::Error, fmt, str::FromStr};

use serde::{
    Deserialize, Deserializer, Serialize, Serializer,
    de::{self, Visitor},
};

const ID_BYTES: usize = 16;
const HEX_BYTES: usize = ID_BYTES * 2;

/// Why a textual stable identity could not be parsed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum IdentityParseError {
    /// The identity does not begin with the prefix for its requested type.
    WrongPrefix {
        /// Prefix required by the requested identity type.
        expected: &'static str,
    },
    /// The hexadecimal payload has the wrong byte length.
    WrongLength {
        /// Required hexadecimal character count.
        expected: usize,
        /// Observed hexadecimal character count.
        actual: usize,
    },
    /// The payload contains a character outside lowercase hexadecimal.
    InvalidHex {
        /// Zero-based position within the hexadecimal payload.
        index: usize,
    },
}

impl fmt::Display for IdentityParseError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::WrongPrefix { expected } => {
                write!(formatter, "identity must begin with {expected}")
            }
            Self::WrongLength { expected, actual } => write!(
                formatter,
                "identity payload must contain {expected} hexadecimal characters, got {actual}"
            ),
            Self::InvalidHex { index } => write!(
                formatter,
                "identity payload contains invalid lowercase hexadecimal at index {index}"
            ),
        }
    }
}

impl Error for IdentityParseError {}

fn decode_nibble(byte: u8, index: usize) -> Result<u8, IdentityParseError> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        _ => Err(IdentityParseError::InvalidHex { index }),
    }
}

macro_rules! stable_identity {
    ($(#[$meta:meta])* $name:ident, $prefix:literal) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd)]
        pub struct $name([u8; ID_BYTES]);

        impl $name {
            /// Constructs an identity from bytes generated by its owning boundary.
            #[must_use]
            pub const fn from_bytes(bytes: [u8; ID_BYTES]) -> Self {
                Self(bytes)
            }

            /// Returns the exact identity bytes.
            #[must_use]
            pub const fn as_bytes(&self) -> &[u8; ID_BYTES] {
                &self.0
            }
        }

        impl FromStr for $name {
            type Err = IdentityParseError;

            fn from_str(value: &str) -> Result<Self, Self::Err> {
                let payload = value
                    .strip_prefix($prefix)
                    .ok_or(IdentityParseError::WrongPrefix { expected: $prefix })?;
                if payload.len() != HEX_BYTES {
                    return Err(IdentityParseError::WrongLength {
                        expected: HEX_BYTES,
                        actual: payload.len(),
                    });
                }

                let mut bytes = [0; ID_BYTES];
                for (index, pair) in payload.as_bytes().chunks_exact(2).enumerate() {
                    let high = decode_nibble(pair[0], index * 2)?;
                    let low = decode_nibble(pair[1], index * 2 + 1)?;
                    bytes[index] = (high << 4) | low;
                }
                Ok(Self(bytes))
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str($prefix)?;
                for byte in self.0 {
                    write!(formatter, "{byte:02x}")?;
                }
                Ok(())
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter
                    .debug_tuple(stringify!($name))
                    .field(&self.to_string())
                    .finish()
            }
        }

        impl Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: Serializer,
            {
                serializer.collect_str(self)
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: Deserializer<'de>,
            {
                struct IdentityVisitor;

                impl Visitor<'_> for IdentityVisitor {
                    type Value = $name;

                    fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                        write!(
                            formatter,
                            "a {} identity followed by 32 lowercase hexadecimal characters",
                            $prefix
                        )
                    }

                    fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
                    where
                        E: de::Error,
                    {
                        value.parse().map_err(E::custom)
                    }
                }

                deserializer.deserialize_str(IdentityVisitor)
            }
        }
    };
}

stable_identity!(
    /// Stable identity persisted by the boundary that admits one Beryl home.
    BerylHomeId,
    "home_"
);
stable_identity!(
    /// Stable identity for one restorable main conversation window.
    WindowId,
    "window_"
);
stable_identity!(
    /// Stable identity for one configured Codex executable runtime.
    RuntimeId,
    "runtime_"
);
stable_identity!(
    /// Stable identity for one configured root.
    RootId,
    "root_"
);
stable_identity!(
    /// Stable identity for one Syndic-owned conversation thread.
    SyndicThreadId,
    "syndic_thread_"
);
stable_identity!(
    /// Stable identity for one immutable Syndic submitted turn.
    SyndicTurnId,
    "syndic_turn_"
);
stable_identity!(
    /// Stable identity for one durable current Syndic draft.
    SyndicDraftId,
    "syndic_draft_"
);
stable_identity!(
    /// Stable identity for one image marker owned by a Syndic draft.
    SyndicDraftMarkerId,
    "syndic_marker_"
);
stable_identity!(
    /// Stable identity for one ordered Syndic turn item.
    SyndicItemId,
    "syndic_item_"
);
stable_identity!(
    /// Stable identity for one durable accepted-input record.
    SyndicAcceptedInputId,
    "syndic_accepted_"
);
stable_identity!(
    /// Stable identity for one durable queued-input record.
    SyndicQueuedInputId,
    "syndic_queued_"
);
stable_identity!(
    /// Stable identity for one durable retry record.
    SyndicRetryRecordId,
    "syndic_retry_"
);
stable_identity!(
    /// Stable identity for one rebuildable Syndic transcript projection.
    SyndicProjectionId,
    "syndic_projection_"
);
stable_identity!(
    /// Stable identity for one admitted cross-domain command.
    CommandId,
    "command_"
);
stable_identity!(
    /// Stable identity used to deduplicate one logical operation.
    IdempotencyKey,
    "idempotency_"
);
stable_identity!(
    /// Stable identity for one durable Beryl orchestration job.
    JobId,
    "job_"
);
stable_identity!(
    /// Stable identity for one admitted branch-resolution intent.
    ResolutionIntentId,
    "resolution_intent_"
);
stable_identity!(
    /// Stable identity for a Windows virtual desktop when the platform exposes it.
    VirtualDesktopId,
    "desktop_"
);
